### ISSUE TITLE
 Cannot find module

### ISSUE THREAD

**Issue by sanchobouillant** [alexkirsz/dispatch-proxy#24]
I got an error when i try to start dispatch.

``` shell
dispatch start

module.js:340
    throw err;
          ^
Error: Cannot find module '/usr/local/lib/node_modules/dispatch-proxy/bin/../lib'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/dispatch-proxy/bin/dispatch.js:2:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

I installed dispatch-proxy with commands:

``` shell
git clone https://github.com/Morhaus/dispatch-proxy.git
cd dispatch-proxy
sudo npm install -g dispatch-proxy
```

``` shell
node --version
v0.10.15
```

``` shell
 uname -a
Linux sancho 3.11.0-14-generic #21-Ubuntu SMP Tue Nov 12 17:04:55 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by sofathitesh** [comment]
i am facing same problem. Your solution is not working. Please help me.

when i run this command 

./node_modules/.bin/grunt


I found this error

bash: ./node_modules/.bin/grunt: No such file or directory

**Comment by Punksolid** [comment]
@sofathitesh to run grunt you need first run `npm install` on the project directory. 
Anyways now it gives me another error. 

```
Running "coffee:compile" (coffee) task
>> src/dispatcher.coffee:5:5: error: Can't reference 'this' before calling super in derived class constructors
>>     @connectionsTotal = 0
>>     ^
>> In file: src/dispatcher.coffee
>> On line: 4
>>     @connectionsTotal = 0
>>     ^
Warning: CoffeeScript failed to compile. Use --force to continue.
```
