### ISSUE TITLE
ENOTFOUND error

### ISSUE THREAD

**Issue by octavarion** [alexkirsz/dispatch-proxy#30]
Hello,
I'm getting the following error when setting up proxy and trying to connect to any website:

HTTP server started on localhost:8080
Dispatching to addresses 192.168.1.100@1
     error [7607a0] clientRequest
           Error: getaddrinfo ENOTFOUND
               at errnoException (dns.js:37:11)
               at Object.onanswer [as oncomplete](dns.js:124:16)
     error [70cb71] clientRequest
           Error: getaddrinfo ENOTFOUND
               at errnoException (dns.js:37:11)
               at Object.onanswer [as oncomplete](dns.js:124:16)
     error [2fd617] clientRequest
           Error: getaddrinfo ENOTFOUND
               at errnoException (dns.js:37:11)
               at Object.onanswer [as oncomplete](dns.js:124:16)

It doesn't matter what iterfaces I select, I always get this error.
Thanks for any help.

**Comment by purugoyal96** [comment]
I am using node v6.11.3 on Windows 10.
I am getting a similar error on requests on a HTTP server.

```
error [72c466] clientRequest
           Error: getaddrinfo ENOTFOUND mvbkmkjplos mvbkmkjplos:80
               at errnoException (dns.js:28:10)
               at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```
