### ISSUE TITLE
error [44f4b1] ???

### ISSUE THREAD

**Issue by magatst** [alexkirsz/dispatch-proxy#91]
I not understood ???
Help me ?!

My console :
-----------------
iMac27:~ magatst$ dispatch list
lo0
    127.0.0.1 (IPv4, internal)
    ::1 (IPv6, internal)
    fe80::1 (IPv6, internal)

en4
    fe80::408:4e18:9b88:de74 (IPv6)
    192.168.0.22 (IPv4)

en1
    fe80::480:1af8:eb35:93da (IPv6)
    192.168.1.100 (IPv4)

utun0
    fe80::e9de:b2e8:c5cc:84d5 (IPv6)

iMac27:~ magatst$ dispatch start --http
HTTP server started on localhost:8080
Dispatching to addresses 192.168.0.22@1, 192.168.1.100@1
     error [44f4b1] clientRequest
           Error: connect ECONNREFUSED 127.0.0.1:80
               at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
     error [73d8cf] clientRequest
           Error: connect ECONNREFUSED 127.0.0.1:80
               at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
     error [14813f] clientRequest
           Error: connect ECONNREFUSED 127.0.0.1:80
               at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
     error [235dcc] clientRequest
           Error: connect ECONNREFUSED 127.0.0.1:80
               at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
-------

**Comment by magatst** [comment]
![Capture d’écran 2019-06-06 à 14 45 11](https://user-images.githubusercontent.com/11654353/59033769-bddf9180-8869-11e9-865c-42be106bca33.png)

**Comment by magatst** [comment]
Ok, I think I understood.
You should insist on properly configuring the web browser or other on the proxy generated by dispach.
For me it was not immediately obvious being beginner.
https://i.imgur.com/wrzHNu5.png
