### ISSUE TITLE
Crash when installing update for MATLAB

### ISSUE THREAD

**Issue by Unknown78** [alexkirsz/dispatch-proxy#92]
It's happened when I try to update MATLAB R2018b into update 5 using this command

> C:\Program Files\MATLAB\R2018b\bin\win64>update_installer.exe -updatepack "X:\x\R2018b\"

After that, there are two connection error on the dispatch log, but haven't crashed yet.

> C:\WINDOWS\system32>dispatch start
> SOCKS server started on localhost:1080
> Dispatching to addresses x.x.x.x@1, x.x.x.x@1
>      error [ab8c83] serverConnection
>            Error: connect EADDRNOTAVAIL 127.0.0.1:32415
>                at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
>      error [fd4ab0] serverConnection
>            Error: connect EADDRNOTAVAIL 127.0.0.1:32415
>                at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)

The MATLAB window that was supposed to show the update installer throwing an error

![image](https://user-images.githubusercontent.com/25132599/64481473-82f14f00-d206-11e9-94dc-1dd37f064a1a.png)

> Failed to load URL http://localhost:32415/ui/install/update_installer/update_installer/index.html?matlabroot=C:\Program%20Files\MATLAB\R2018b&helper_launch_path=C:\Users\x\AppData\Local\Temp\mw_F112.tmp&updatepack=X:\x\R2018b with error ERR_SOCKS_CONNECTION_FAILED (-120).

After I closed the window, the dispatch process crashed, here is the cmd log

> events.js:174
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: read ECONNRESET
>     at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
> Emitted 'error' event at:
>     at emitErrorNT (internal/streams/destroy.js:91:8)
>     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
>
> C:\WINDOWS\system32>

Here is the correct MATLAB update window.
![image](https://user-images.githubusercontent.com/25132599/64481530-41ad6f00-d207-11e9-95da-e9d05e2de151.png)

Here is my system proxy settings
![image](https://user-images.githubusercontent.com/25132599/64481544-abc61400-d207-11e9-8ca3-f41fb456e39b.png)

While it is not a critical bug because I could still successfully update without any problem by turning off my proxy, but still, I would like to report it here.

**Comment by Unknown78** [comment]
"Don't use the proxy server for local (intranet) addresses" option seems to be worked.

I think to solve this bug involves some kind of prevention from "Unhandled 'error' event" crashing, when the user use proxy for local addresses.
